<?php

echo '<div class="topOfPage"><a href="#topP">CLICK HERE TO RETURN TO TOP OF PAGE</a></div>
    </div>
    <footer>
        <!-- here is the code for setting up the footer, in wide view, the link footer is between the leftfooter and rightfooter, 
            but when in a smaller view, linkfooter re-aligns beneath the other footer classes -->
        <section class="leftfooter">
            <p>COPYRIGHT &copy; 2023 SwinNet Pty Ltd</p>
            <p>All rights reserved</p><br><br><br>
        </section>
        <section class="rightfooter">
            <p>CONTACT:</p>
            <p>Available 9AM - 5PM Weekdays</p>
            <p>04 0404 0404</p>
            <p>123 Swinburne Street</p><br>
        </section>
        <section class="linkfooter">
            <h3>PROJECT CREATED BY:</h3>
            <p>
                <a href="mailto:104554365@student.swin.edu.au">Emily Hocking</a><br>
                <a href="mailto:104540555@student.swin.edu.au">Tessa Mordue</a><br>
                <a href="mailto:104022163@student.swin.edu.au">Finbarr Brennan</a><br>
                <a href="mailto:104188984@student.swin.edu.au">Nisha Purumandla</a><br>
                <a href="mailto:104322960@student.swin.edu.au">Keshav Arora</a><br><br>
            </p>
        </section>
    </footer>';
	
?>